"""Map country names to ISO-2 codes and to flag emojis."""

COUNTRY_TO_ISO2 = {
    "Italy": "IT",
    "Italia": "IT",
    "Spain": "ES",
    "España": "ES",
    "France": "FR",
    "Germany": "DE",
    "Deutschland": "DE",
    "England": "GB",
    "United Kingdom": "GB",
    "Scotland": "GB",
    "Wales": "GB",
    "Northern Ireland": "GB",
    "Ireland": "IE",
    "Portugal": "PT",
    "Netherlands": "NL",
    "Holland": "NL",
    "Belgium": "BE",
    "Switzerland": "CH",
    "Austria": "AT",
    "Poland": "PL",
    "Denmark": "DK",
    "Sweden": "SE",
    "Norway": "NO",
    "Finland": "FI",
    "Iceland": "IS",
    "Croatia": "HR",
    "Serbia": "RS",
    "Bosnia-Herzegovina": "BA",
    "Slovenia": "SI",
    "Slovakia": "SK",
    "Czech Republic": "CZ",
    "Czechia": "CZ",
    "Hungary": "HU",
    "Romania": "RO",
    "Bulgaria": "BG",
    "Greece": "GR",
    "Turkey": "TR",
    "Türkiye": "TR",
    "Ukraine": "UA",
    "Russia": "RU",
    "Belarus": "BY",
    "Albania": "AL",
    "Kosovo": "XK",
    "North Macedonia": "MK",
    "Montenegro": "ME",
    "Estonia": "EE",
    "Latvia": "LV",
    "Lithuania": "LT",
    "Argentina": "AR",
    "Brazil": "BR",
    "Brasil": "BR",
    "Uruguay": "UY",
    "Paraguay": "PY",
    "Chile": "CL",
    "Colombia": "CO",
    "Peru": "PE",
    "Ecuador": "EC",
    "Venezuela": "VE",
    "Bolivia": "BO",
    "Mexico": "MX",
    "United States": "US",
    "USA": "US",
    "Canada": "CA",
    "Costa Rica": "CR",
    "Panama": "PA",
    "Honduras": "HN",
    "Guatemala": "GT",
    "Jamaica": "JM",
    "Japan": "JP",
    "South Korea": "KR",
    "Korea, South": "KR",
    "Korea Republic": "KR",
    "China": "CN",
    "Australia": "AU",
    "New Zealand": "NZ",
    "Saudi Arabia": "SA",
    "Iran": "IR",
    "Iraq": "IQ",
    "Qatar": "QA",
    "United Arab Emirates": "AE",
    "UAE": "AE",
    "Morocco": "MA",
    "Algeria": "DZ",
    "Tunisia": "TN",
    "Egypt": "EG",
    "Nigeria": "NG",
    "Ghana": "GH",
    "Senegal": "SN",
    "Ivory Coast": "CI",
    "Côte d'Ivoire": "CI",
    "Cameroon": "CM",
    "Mali": "ML",
    "South Africa": "ZA",
    "Kenya": "KE",
    "Ethiopia": "ET",
    "DR Congo": "CD",
    "Congo DR": "CD",
    "Angola": "AO",
    "Uzbekistan": "UZ",
    "Azerbaijan": "AZ",
    "Georgia": "GE",
    "Armenia": "AM",
    "Israel": "IL",
    "India": "IN",
    "Thailand": "TH",
    "Vietnam": "VN",
    "Indonesia": "ID",
    "Philippines": "PH",
}


def country_to_flag(country: str) -> str:
    """Return a flag emoji for a country name, or empty string if unknown."""
    if not country:
        return ""
    iso = COUNTRY_TO_ISO2.get(country.strip())
    if not iso:
        return ""
    if iso == "GB":
        # Real UK flag emoji
        return "🇬🇧"
    if iso == "XK":
        return "🇽🇰"
    # Regional indicator symbols: A=0x1F1E6
    return "".join(chr(0x1F1E6 + ord(c) - ord("A")) for c in iso.upper())
